---
title: "Assignment7"
author: "Ingrid Jacobson"
date: "`r Sys.Date()`"
output: html_document
---

## Task One: Set-up

```{r, include = FALSE, results='hide'}
#Task 1: Set up
library(tidyverse)
library(data.table)
library(lubridate)
library(googledrive)
source("sepsis_monitor_functions.R")

```

## Task 2: Speed Reading

```{r, echo = FALSE, results = 'hide'}
library(tictoc)
source("sepsis_monitor_functions.R")

tic()
sepsis_data_50_fread <- makeSepsisDataset(n = 50, read_fn = "fread")
toc()

tic()
sepsis_data_50_delim <- makeSepsisDataset(n = 50, read_fn = "read_delim")
toc()

tic()
sepsis_data_100_fread <- makeSepsisDataset(n = 100, read_fn = "fread")
toc()

tic()
sepsis_data_100_delim <- makeSepsisDataset(n = 100, read_fn = "read_delim")
toc()

tic()
sepsis_data_500_fread <- makeSepsisDataset(n = 500, read_fn = "fread")
toc()

tic()
sepsis_data_500_delim <- makeSepsisDataset(n = 500, read_fn = "read_delim")
toc()


```

#### Timing Results:

|                | 50 patients    | 100 patients   | 500 patients    |
|----------------|----------------|----------------|-----------------|
| **fread**      | 4.502 seconds  | 9.168 seconds  | 48.911 seconds  |
| **read_delim** | 18.235 seconds | 36.397 seconds | 180.822 seconds |

### Task 3: Google Drive

```{r, results='hide'}
library(googledrive)
source("sepsis_monitor_functions.R")

library(googledrive)

# Set the path to the JSON file
json_file <- "sepsis_client_id.json"

# Authenticate with the Google Drive API using the JSON file
drive_auth(path = json_file)

# Check that authentication was successful
drive_about()

# Create the sepsis dataset
df <- makeSepsisDataset()

# Write the dataset to a temporary CSV file
write_csv(df, "sepsis_data_temp.csv")

# Upload the file to the specified folder
sepsis_file <- drive_upload(
  "sepsis_data_temp.csv",
  path = "1qTts4tUO6ExMNQ9-ujCZMU0H5ChKt9RJ",
  type = "text/csv"
)

# Set the file permissions so anyone can download this file
drive_share_anyone(sepsis_file)



```

```{r, results='hide'}
sepsis_file <- drive_upload(media = "sepsis_data_temp.csv",
                            name = "sepsis_data.csv",
                            type = "text/csv",
                            path = "sepsis_data_folder")

```

### Task 4: Make an ICU Status Report

```{r}
library(googledrive)
library(tidyverse)
library(gargle)
source("sepsis_monitor_functions.R")

## Calling drive_deauth() prevents R from trying to authenticate via a browser
## This is needed to make the GitHub Action work
drive_deauth()
file_link <- "usZYPexIDGTtAc6oFm5UYg0PfXBUPP6W"


## All data up until now
new_data <- updateData(file_link) #This part is not working, why?

## Include only most recent data
most_recent_data <- new_data %>%
  group_by(PatientID) %>%
  filter(obsTime == max(obsTime))
```

```{r}
## Determine which patients currently have sepsis
sepsis_patients <- getSepsisPatients(most_recent_data)

## Create table listing physiological data for sepsis patients
sepsis_table <- most_recent_data %>%
  filter(PatientID %in% sepsis_patients) %>%
  select(PatientID, HeartRate, Temperature, RespiratoryRate) %>%
  rename(`Heart Rate` = HeartRate, `Respiratory Rate` = RespiratoryRate)

## Add timestamp to table
timestamp <- format(Sys.time(), "%Y-%m-%d %H:%M:%S")
sepsis_table <- bind_rows(list(PatientID = NA, `Heart Rate` = NA, Temperature = NA, `Respiratory Rate` = NA),
                          sepsis_table)
sepsis_table[1, ] <- list(PatientID = "Report generated at:", `Heart Rate` = timestamp, Temperature = "", `Respiratory Rate` = "")

```

```{r}
## Create plots for patients with sepsis
for (patient in sepsis_patients) {
  patient_data <- most_recent_data %>%
    filter(PatientID == patient) %>%
    select(obsTime, HeartRate, Temperature, RespiratoryRate)

  ## Heart rate plot
  hr_plot <- ggplot(patient_data, aes(x = obsTime, y = HeartRate)) +
    geom_line() +
    labs(title = paste("Heart Rate for Patient ", patient), x = "Time", y = "Heart Rate")

  ## Temperature plot
  temp_plot <- ggplot(patient_data, aes(x = obsTime, y = Temperature)) +
    geom_line() +
    labs(title = paste("Temperature for Patient ", patient), x = "Time", y = "Temperature")

  ## Respiratory rate plot
  rr_plot <- ggplot(patient_data, aes(x = obsTime, y = RespiratoryRate)) +
    geom_line() +
    labs(title = paste("Respiratory Rate for Patient ", patient), x = "Time", y = "Respiratory Rate")

  ## Print plots
  print(hr_plot)
  print(temp_plot)
  print(rr_plot)
}

```

```{r}
## Share report with anyone who has the link
report_file <- drive_upload(html_report, name = "ICU_Status_Report.html", type = "text/html", path = "ICU Status Reports")
drive_share_anyone(report_file)
```

```{r}

```
