name: Render ICU Status Report

on:
  schedule:
    - cron: "0 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up R
        uses: r-lib/actions/setup-r@v1
        with:
          r-version: "4.1.0"
      - name: Install R packages
        run: |
          Rscript -e "install.packages(c('tidyverse', 'data.table', 'lubridate', 'googledrive'))"
      - name: Render ICU Status Report
        run: Rscript -e "rmarkdown::render('icu_status_report.Rmd')"
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update ICU status report"
          commit_options: "--author='GitHub Action <>'"
